version: 2
updates:
  - package-ecosystem: npm
    directory: /services/agent
    schedule:
      interval: monthly
    groups:
      all-npm:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /services/control-plane
    schedule:
      interval: monthly
    groups:
      all-go:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /services/github-bot
    schedule:
      interval: monthly
    groups:
      all-go:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /services/secret-proxy
    schedule:
      interval: monthly
    groups:
      all-go:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /clients/cli
    schedule:
      interval: monthly
    groups:
      all-go:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /services/agent/auth-proxy
    schedule:
      interval: monthly
    groups:
      all-go:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all-actions:
        patterns:
          - "*"
